// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SeidoDemoDb;

#nullable disable

namespace BlackPearl.Migrations
{
    [DbContext(typeof(PearlDbContext))]
    [Migration("20220314092829_two")]
    partial class two
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.3");

            modelBuilder.Entity("BlackPearl.Pearl", b =>
                {
                    b.Property<int>("PearlID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .HasColumnType("TEXT");

                    b.Property<int>("Diameter")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Price")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Shape")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.HasKey("PearlID");

                    b.ToTable("Pearls");
                });

            modelBuilder.Entity("BlackPearl.PearlList", b =>
                {
                    b.Property<int>("PearlListID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("PearlID")
                        .HasColumnType("INTEGER");

                    b.HasKey("PearlListID");

                    b.ToTable("PearlLists");
                });
#pragma warning restore 612, 618
        }
    }
}
